import _ from "lodash"; // _ represents lodash
import { FETCH_POST, FETCH_POSTS, CREATE_POST, DELETE_POST } from '../actions/index';

export default function(state = {}, action) {
  switch (action.type) {
    case FETCH_POST:
      // ES5
      // fetched post
      //const post = action.payload.data;
      // we don't lose previously fetched posts we add this new post to app state
      //const newState =  { ...state };
      //newState[post.id] = post;
      //return newState;
      // ES6
      return { ...state, [action.payload.data.id]: action.payload.data };
    case FETCH_POSTS:
      // creates an object with the same values as object and keys generated by
      // running each own enumerable string keyed property of object thru iteratee
      return _.mapKeys(action.payload.data, "id");
    case CREATE_POST:
      return state;
    case DELETE_POST:
      // delete post with id from state (id on payload)
      return _.omit(state, action.payload);

    default:
      return state;
    }
}
